apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: shoppingscraper
spec:
  schedule: "0 0 * * 1,4"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: shopping
            image: giorgiocarta/shopping_offers_scraper:latest
            env:
            - name: ES_URL
              value: "elasticsearch"
            - name: ES_PORT
              value: "9200"
            - name: ES_INDEX
              value: "special_offers"